//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.DigitalSubscription
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Application user.
    /// </summary>
    //  *** Start programmer edit section *** (ApplicationUser CustomAttributes)

    //  *** End programmer edit section *** (ApplicationUser CustomAttributes)
    [PublishName("ApplicationUser")]
    [AutoAltered()]
    [Caption("Пользователь")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ApplicationUserE", new string[] {
            "Email as \'Email\'",
            "LastName as \'Фамилия\'",
            "FirstName as \'Имя\'",
            "MiddleName as \'Отчество\'",
            "Birthdate as \'Дата рождения\'"})]
    [View("ApplicationUserL", new string[] {
            "Email as \'Email\'",
            "LastName as \'Фамилия\'",
            "FirstName as \'Имя\'",
            "MiddleName as \'Отчество\'",
            "Birthdate as \'Дата рождения\'"})]
    public class ApplicationUser : ICSSoft.STORMNET.DataObject
    {
        
        private string fEmail;
        
        private string fFirstName;
        
        private string fMiddleName;
        
        private string fLastName;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fBirthdate;
        
        private bool fIsAdmin = false;
        
        //  *** Start programmer edit section *** (ApplicationUser CustomMembers)

        //  *** End programmer edit section *** (ApplicationUser CustomMembers)

        
        /// <summary>
        /// Электронная почта.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.Email CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.Email CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Email
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.Email Get start)

                //  *** End programmer edit section *** (ApplicationUser.Email Get start)
                string result = this.fEmail;
                //  *** Start programmer edit section *** (ApplicationUser.Email Get end)

                //  *** End programmer edit section *** (ApplicationUser.Email Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.Email Set start)

                //  *** End programmer edit section *** (ApplicationUser.Email Set start)
                this.fEmail = value;
                //  *** Start programmer edit section *** (ApplicationUser.Email Set end)

                //  *** End programmer edit section *** (ApplicationUser.Email Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.FirstName CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.FirstName CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string FirstName
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.FirstName Get start)

                //  *** End programmer edit section *** (ApplicationUser.FirstName Get start)
                string result = this.fFirstName;
                //  *** Start programmer edit section *** (ApplicationUser.FirstName Get end)

                //  *** End programmer edit section *** (ApplicationUser.FirstName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.FirstName Set start)

                //  *** End programmer edit section *** (ApplicationUser.FirstName Set start)
                this.fFirstName = value;
                //  *** Start programmer edit section *** (ApplicationUser.FirstName Set end)

                //  *** End programmer edit section *** (ApplicationUser.FirstName Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.MiddleName CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.MiddleName CustomAttributes)
        [StrLen(255)]
        public virtual string MiddleName
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.MiddleName Get start)

                //  *** End programmer edit section *** (ApplicationUser.MiddleName Get start)
                string result = this.fMiddleName;
                //  *** Start programmer edit section *** (ApplicationUser.MiddleName Get end)

                //  *** End programmer edit section *** (ApplicationUser.MiddleName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.MiddleName Set start)

                //  *** End programmer edit section *** (ApplicationUser.MiddleName Set start)
                this.fMiddleName = value;
                //  *** Start programmer edit section *** (ApplicationUser.MiddleName Set end)

                //  *** End programmer edit section *** (ApplicationUser.MiddleName Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.LastName CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.LastName CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string LastName
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.LastName Get start)

                //  *** End programmer edit section *** (ApplicationUser.LastName Get start)
                string result = this.fLastName;
                //  *** Start programmer edit section *** (ApplicationUser.LastName Get end)

                //  *** End programmer edit section *** (ApplicationUser.LastName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.LastName Set start)

                //  *** End programmer edit section *** (ApplicationUser.LastName Set start)
                this.fLastName = value;
                //  *** Start programmer edit section *** (ApplicationUser.LastName Set end)

                //  *** End programmer edit section *** (ApplicationUser.LastName Set end)
            }
        }
        
        /// <summary>
        /// Дата рождения.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.Birthdate CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.Birthdate CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime Birthdate
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.Birthdate Get start)

                //  *** End programmer edit section *** (ApplicationUser.Birthdate Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fBirthdate;
                //  *** Start programmer edit section *** (ApplicationUser.Birthdate Get end)

                //  *** End programmer edit section *** (ApplicationUser.Birthdate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.Birthdate Set start)

                //  *** End programmer edit section *** (ApplicationUser.Birthdate Set start)
                this.fBirthdate = value;
                //  *** Start programmer edit section *** (ApplicationUser.Birthdate Set end)

                //  *** End programmer edit section *** (ApplicationUser.Birthdate Set end)
            }
        }
        
        /// <summary>
        /// Администратор.
        /// </summary>
        //  *** Start programmer edit section *** (ApplicationUser.IsAdmin CustomAttributes)

        //  *** End programmer edit section *** (ApplicationUser.IsAdmin CustomAttributes)
        [NotNull()]
        public virtual bool IsAdmin
        {
            get
            {
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Get start)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Get start)
                bool result = this.fIsAdmin;
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Get end)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Set start)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Set start)
                this.fIsAdmin = value;
                //  *** Start programmer edit section *** (ApplicationUser.IsAdmin Set end)

                //  *** End programmer edit section *** (ApplicationUser.IsAdmin Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ApplicationUserE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationUserE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationUserE", typeof(NewPlatform.DigitalSubscription.ApplicationUser));
                }
            }
            
            /// <summary>
            /// "ApplicationUserL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationUserL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationUserL", typeof(NewPlatform.DigitalSubscription.ApplicationUser));
                }
            }
        }
    }
}
