//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.DigitalSubscription
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Employee in organization.
    /// </summary>
    //  *** Start programmer edit section *** (EmployeeInOrganization CustomAttributes)

    //  *** End programmer edit section *** (EmployeeInOrganization CustomAttributes)
    [PublishName("EmployeeInOrganization")]
    [AutoAltered()]
    [Caption("Сотрудник организации")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EmployeeInOrganizationE", new string[] {
            "EmploymentDate as \'Дата приёма на работу\'",
            "DismissalDate as \'Дата увольнения\'",
            "Position as \'Должность\'",
            "IsAdmin as \'Администратор\'",
            "Employee as \'Email пользователя\'",
            "Employee.Email as \'Email\'",
            "Employee.LastName as \'Фамилия\'",
            "Employee.FirstName as \'Имя\'",
            "Employee.MiddleName as \'Отчество\'"}, Hidden=new string[] {
            "Employee.Email"})]
    [MasterViewDefineAttribute("EmployeeInOrganizationE", "Employee", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Email")]
    public class EmployeeInOrganization : ICSSoft.STORMNET.DataObject
    {
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fEmploymentDate = ICSSoft.STORMNET.UserDataTypes.NullableDateTime.Now;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fDismissalDate;
        
        private string fPosition;
        
        private bool fIsAdmin = false;
        
        private NewPlatform.DigitalSubscription.ApplicationUser fEmployee;
        
        private NewPlatform.DigitalSubscription.Organization fOrganization;
        
        //  *** Start programmer edit section *** (EmployeeInOrganization CustomMembers)

        //  *** End programmer edit section *** (EmployeeInOrganization CustomMembers)

        
        /// <summary>
        /// Дата приёма на работу.
        /// </summary>
        //  *** Start programmer edit section *** (EmployeeInOrganization.EmploymentDate CustomAttributes)

        //  *** End programmer edit section *** (EmployeeInOrganization.EmploymentDate CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime EmploymentDate
        {
            get
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.EmploymentDate Get start)

                //  *** End programmer edit section *** (EmployeeInOrganization.EmploymentDate Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fEmploymentDate;
                //  *** Start programmer edit section *** (EmployeeInOrganization.EmploymentDate Get end)

                //  *** End programmer edit section *** (EmployeeInOrganization.EmploymentDate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.EmploymentDate Set start)

                //  *** End programmer edit section *** (EmployeeInOrganization.EmploymentDate Set start)
                this.fEmploymentDate = value;
                //  *** Start programmer edit section *** (EmployeeInOrganization.EmploymentDate Set end)

                //  *** End programmer edit section *** (EmployeeInOrganization.EmploymentDate Set end)
            }
        }
        
        /// <summary>
        /// Дата увольнения.
        /// </summary>
        //  *** Start programmer edit section *** (EmployeeInOrganization.DismissalDate CustomAttributes)

        //  *** End programmer edit section *** (EmployeeInOrganization.DismissalDate CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime DismissalDate
        {
            get
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.DismissalDate Get start)

                //  *** End programmer edit section *** (EmployeeInOrganization.DismissalDate Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fDismissalDate;
                //  *** Start programmer edit section *** (EmployeeInOrganization.DismissalDate Get end)

                //  *** End programmer edit section *** (EmployeeInOrganization.DismissalDate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.DismissalDate Set start)

                //  *** End programmer edit section *** (EmployeeInOrganization.DismissalDate Set start)
                this.fDismissalDate = value;
                //  *** Start programmer edit section *** (EmployeeInOrganization.DismissalDate Set end)

                //  *** End programmer edit section *** (EmployeeInOrganization.DismissalDate Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        //  *** Start programmer edit section *** (EmployeeInOrganization.Position CustomAttributes)

        //  *** End programmer edit section *** (EmployeeInOrganization.Position CustomAttributes)
        [StrLen(255)]
        public virtual string Position
        {
            get
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.Position Get start)

                //  *** End programmer edit section *** (EmployeeInOrganization.Position Get start)
                string result = this.fPosition;
                //  *** Start programmer edit section *** (EmployeeInOrganization.Position Get end)

                //  *** End programmer edit section *** (EmployeeInOrganization.Position Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.Position Set start)

                //  *** End programmer edit section *** (EmployeeInOrganization.Position Set start)
                this.fPosition = value;
                //  *** Start programmer edit section *** (EmployeeInOrganization.Position Set end)

                //  *** End programmer edit section *** (EmployeeInOrganization.Position Set end)
            }
        }
        
        /// <summary>
        /// Администратор организации.
        /// </summary>
        //  *** Start programmer edit section *** (EmployeeInOrganization.IsAdmin CustomAttributes)

        //  *** End programmer edit section *** (EmployeeInOrganization.IsAdmin CustomAttributes)
        [NotNull()]
        public virtual bool IsAdmin
        {
            get
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.IsAdmin Get start)

                //  *** End programmer edit section *** (EmployeeInOrganization.IsAdmin Get start)
                bool result = this.fIsAdmin;
                //  *** Start programmer edit section *** (EmployeeInOrganization.IsAdmin Get end)

                //  *** End programmer edit section *** (EmployeeInOrganization.IsAdmin Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.IsAdmin Set start)

                //  *** End programmer edit section *** (EmployeeInOrganization.IsAdmin Set start)
                this.fIsAdmin = value;
                //  *** Start programmer edit section *** (EmployeeInOrganization.IsAdmin Set end)

                //  *** End programmer edit section *** (EmployeeInOrganization.IsAdmin Set end)
            }
        }
        
        /// <summary>
        /// Employee in organization.
        /// </summary>
        //  *** Start programmer edit section *** (EmployeeInOrganization.Employee CustomAttributes)

        //  *** End programmer edit section *** (EmployeeInOrganization.Employee CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.DigitalSubscription.ApplicationUser Employee
        {
            get
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.Employee Get start)

                //  *** End programmer edit section *** (EmployeeInOrganization.Employee Get start)
                NewPlatform.DigitalSubscription.ApplicationUser result = this.fEmployee;
                //  *** Start programmer edit section *** (EmployeeInOrganization.Employee Get end)

                //  *** End programmer edit section *** (EmployeeInOrganization.Employee Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.Employee Set start)

                //  *** End programmer edit section *** (EmployeeInOrganization.Employee Set start)
                this.fEmployee = value;
                //  *** Start programmer edit section *** (EmployeeInOrganization.Employee Set end)

                //  *** End programmer edit section *** (EmployeeInOrganization.Employee Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.DigitalSubscription.Organization.
        /// </summary>
        //  *** Start programmer edit section *** (EmployeeInOrganization.Organization CustomAttributes)

        //  *** End programmer edit section *** (EmployeeInOrganization.Organization CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Organization"})]
        public virtual NewPlatform.DigitalSubscription.Organization Organization
        {
            get
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.Organization Get start)

                //  *** End programmer edit section *** (EmployeeInOrganization.Organization Get start)
                NewPlatform.DigitalSubscription.Organization result = this.fOrganization;
                //  *** Start programmer edit section *** (EmployeeInOrganization.Organization Get end)

                //  *** End programmer edit section *** (EmployeeInOrganization.Organization Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (EmployeeInOrganization.Organization Set start)

                //  *** End programmer edit section *** (EmployeeInOrganization.Organization Set start)
                this.fOrganization = value;
                //  *** Start programmer edit section *** (EmployeeInOrganization.Organization Set end)

                //  *** End programmer edit section *** (EmployeeInOrganization.Organization Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EmployeeInOrganizationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeInOrganizationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeInOrganizationE", typeof(NewPlatform.DigitalSubscription.EmployeeInOrganization));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of EmployeeInOrganization.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfEmployeeInOrganization CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfEmployeeInOrganization CustomAttributes)
    public class DetailArrayOfEmployeeInOrganization : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (NewPlatform.DigitalSubscription.DetailArrayOfEmployeeInOrganization members)

        //  *** End programmer edit section *** (NewPlatform.DigitalSubscription.DetailArrayOfEmployeeInOrganization members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type EmployeeInOrganization by index.
        /// </summary>
        /// <summary>
        /// Adds object with type EmployeeInOrganization.
        /// </summary>
        public DetailArrayOfEmployeeInOrganization(NewPlatform.DigitalSubscription.Organization fOrganization) : 
                base(typeof(EmployeeInOrganization), ((ICSSoft.STORMNET.DataObject)(fOrganization)))
        {
        }
        
        public NewPlatform.DigitalSubscription.EmployeeInOrganization this[int index]
        {
            get
            {
                return ((NewPlatform.DigitalSubscription.EmployeeInOrganization)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.DigitalSubscription.EmployeeInOrganization dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
