//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.DigitalSubscription
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Price period.
    /// </summary>
    //  *** Start programmer edit section *** (PricePeriod CustomAttributes)

    //  *** End programmer edit section *** (PricePeriod CustomAttributes)
    public enum PricePeriod
    {
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (PricePeriod.Day CustomAttributes)

        //  *** End programmer edit section *** (PricePeriod.Day CustomAttributes)
        [Caption("День")]
        Day,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (PricePeriod.Week CustomAttributes)

        //  *** End programmer edit section *** (PricePeriod.Week CustomAttributes)
        [Caption("Неделя")]
        Week,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (PricePeriod.Month CustomAttributes)

        //  *** End programmer edit section *** (PricePeriod.Month CustomAttributes)
        [Caption("Месяц")]
        Month,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (PricePeriod.ThreeMonth CustomAttributes)

        //  *** End programmer edit section *** (PricePeriod.ThreeMonth CustomAttributes)
        [Caption("3 месяца")]
        ThreeMonth,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (PricePeriod.SixMonth CustomAttributes)

        //  *** End programmer edit section *** (PricePeriod.SixMonth CustomAttributes)
        [Caption("6 месяцев")]
        SixMonth,
        
        /// <summary>
        /// 
        /// </summary>
        //  *** Start programmer edit section *** (PricePeriod.Year CustomAttributes)

        //  *** End programmer edit section *** (PricePeriod.Year CustomAttributes)
        [Caption("Год")]
        Year,
    }
}
