//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.DigitalSubscription
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Service.
    /// </summary>
    //  *** Start programmer edit section *** (Service CustomAttributes)

    //  *** End programmer edit section *** (Service CustomAttributes)
    [PublishName("Service")]
    [AutoAltered()]
    [Caption("Услуга")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ServiceE", new string[] {
            "Name as \'Название\'",
            "Price as \'Стоимость\'",
            "PricePeriod as \'Период\'"})]
    [View("ServiceL", new string[] {
            "Name as \'Название\'",
            "Price as \'Стоимость\'",
            "PricePeriod as \'Период\'",
            "Organization"}, Hidden=new string[] {
            "Organization"})]
    public class Service : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private double fPrice = 0D;
        
        private NewPlatform.DigitalSubscription.PricePeriod fPricePeriod = NewPlatform.DigitalSubscription.PricePeriod.Month;
        
        private NewPlatform.DigitalSubscription.Organization fOrganization;
        
        //  *** Start programmer edit section *** (Service CustomMembers)

        //  *** End programmer edit section *** (Service CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Service.Name CustomAttributes)

        //  *** End programmer edit section *** (Service.Name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Service.Name Get start)

                //  *** End programmer edit section *** (Service.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Service.Name Get end)

                //  *** End programmer edit section *** (Service.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Service.Name Set start)

                //  *** End programmer edit section *** (Service.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Service.Name Set end)

                //  *** End programmer edit section *** (Service.Name Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        //  *** Start programmer edit section *** (Service.Price CustomAttributes)

        //  *** End programmer edit section *** (Service.Price CustomAttributes)
        [NotNull()]
        public virtual double Price
        {
            get
            {
                //  *** Start programmer edit section *** (Service.Price Get start)

                //  *** End programmer edit section *** (Service.Price Get start)
                double result = this.fPrice;
                //  *** Start programmer edit section *** (Service.Price Get end)

                //  *** End programmer edit section *** (Service.Price Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Service.Price Set start)

                //  *** End programmer edit section *** (Service.Price Set start)
                this.fPrice = value;
                //  *** Start programmer edit section *** (Service.Price Set end)

                //  *** End programmer edit section *** (Service.Price Set end)
            }
        }
        
        /// <summary>
        /// Стоимость за период.
        /// </summary>
        //  *** Start programmer edit section *** (Service.PricePeriod CustomAttributes)

        //  *** End programmer edit section *** (Service.PricePeriod CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.DigitalSubscription.PricePeriod PricePeriod
        {
            get
            {
                //  *** Start programmer edit section *** (Service.PricePeriod Get start)

                //  *** End programmer edit section *** (Service.PricePeriod Get start)
                NewPlatform.DigitalSubscription.PricePeriod result = this.fPricePeriod;
                //  *** Start programmer edit section *** (Service.PricePeriod Get end)

                //  *** End programmer edit section *** (Service.PricePeriod Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Service.PricePeriod Set start)

                //  *** End programmer edit section *** (Service.PricePeriod Set start)
                this.fPricePeriod = value;
                //  *** Start programmer edit section *** (Service.PricePeriod Set end)

                //  *** End programmer edit section *** (Service.PricePeriod Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.DigitalSubscription.Organization.
        /// </summary>
        //  *** Start programmer edit section *** (Service.Organization CustomAttributes)

        //  *** End programmer edit section *** (Service.Organization CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual NewPlatform.DigitalSubscription.Organization Organization
        {
            get
            {
                //  *** Start programmer edit section *** (Service.Organization Get start)

                //  *** End programmer edit section *** (Service.Organization Get start)
                NewPlatform.DigitalSubscription.Organization result = this.fOrganization;
                //  *** Start programmer edit section *** (Service.Organization Get end)

                //  *** End programmer edit section *** (Service.Organization Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Service.Organization Set start)

                //  *** End programmer edit section *** (Service.Organization Set start)
                this.fOrganization = value;
                //  *** Start programmer edit section *** (Service.Organization Set end)

                //  *** End programmer edit section *** (Service.Organization Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ServiceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ServiceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ServiceE", typeof(NewPlatform.DigitalSubscription.Service));
                }
            }
            
            /// <summary>
            /// "ServiceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ServiceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ServiceL", typeof(NewPlatform.DigitalSubscription.Service));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Service.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfService CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfService CustomAttributes)
    public class DetailArrayOfService : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (NewPlatform.DigitalSubscription.DetailArrayOfService members)

        //  *** End programmer edit section *** (NewPlatform.DigitalSubscription.DetailArrayOfService members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Service by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Service.
        /// </summary>
        public DetailArrayOfService(NewPlatform.DigitalSubscription.Organization fOrganization) : 
                base(typeof(Service), ((ICSSoft.STORMNET.DataObject)(fOrganization)))
        {
        }
        
        public NewPlatform.DigitalSubscription.Service this[int index]
        {
            get
            {
                return ((NewPlatform.DigitalSubscription.Service)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.DigitalSubscription.Service dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
