//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.DigitalSubscription
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Subscription.
    /// </summary>
    //  *** Start programmer edit section *** (Subscription CustomAttributes)

    //  *** End programmer edit section *** (Subscription CustomAttributes)
    [PublishName("Subscription")]
    [AutoAltered()]
    [Caption("Абонемент")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SubscriptionE", new string[] {
            "StartTime as \'Дата начала\'",
            "EndTime as \'Дата окончания\'",
            "ServiceCount as \'Количество\'",
            "Client as \'Клиент\'",
            "Client.LastName as \'Фамилия\'",
            "Client.FirstName as \'Имя\'",
            "Client.MiddleName as \'Отчество\'",
            "Client.Birthdate as \'Дата рождения\'",
            "Client.Email",
            "Service as \'Услуга\'",
            "Service.Name as \'Name\'"}, Hidden=new string[] {
            "Client.Email",
            "Service.Name"})]
    [MasterViewDefineAttribute("SubscriptionE", "Client", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Email")]
    [MasterViewDefineAttribute("SubscriptionE", "Service", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("SubscriptionL", new string[] {
            "Client.LastName as \'Фамилия клиента\'",
            "Client.FirstName as \'Имя клиента\'",
            "Client.MiddleName as \'Отчество клиента\'",
            "Client.Birthdate as \'ДР клиента\'",
            "Client.Email as \'Email клиента\'",
            "StartTime as \'С\'",
            "EndTime as \'По\'",
            "ServiceCount as \'Кол-во\'",
            "Service.Name as \'Услуга\'"})]
    public class Subscription : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fStartTime = System.DateTime.Now;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fEndTime;
        
        private double fServiceCount = 0D;
        
        private NewPlatform.DigitalSubscription.Service fService;
        
        private NewPlatform.DigitalSubscription.ApplicationUser fClient;
        
        //  *** Start programmer edit section *** (Subscription CustomMembers)

        //  *** End programmer edit section *** (Subscription CustomMembers)

        
        /// <summary>
        /// Начало действия.
        /// </summary>
        //  *** Start programmer edit section *** (Subscription.StartTime CustomAttributes)

        //  *** End programmer edit section *** (Subscription.StartTime CustomAttributes)
        [NotNull()]
        public virtual System.DateTime StartTime
        {
            get
            {
                //  *** Start programmer edit section *** (Subscription.StartTime Get start)

                //  *** End programmer edit section *** (Subscription.StartTime Get start)
                System.DateTime result = this.fStartTime;
                //  *** Start programmer edit section *** (Subscription.StartTime Get end)

                //  *** End programmer edit section *** (Subscription.StartTime Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Subscription.StartTime Set start)

                //  *** End programmer edit section *** (Subscription.StartTime Set start)
                this.fStartTime = value;
                //  *** Start programmer edit section *** (Subscription.StartTime Set end)

                //  *** End programmer edit section *** (Subscription.StartTime Set end)
            }
        }
        
        /// <summary>
        /// Конец действия.
        /// </summary>
        //  *** Start programmer edit section *** (Subscription.EndTime CustomAttributes)

        //  *** End programmer edit section *** (Subscription.EndTime CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime EndTime
        {
            get
            {
                //  *** Start programmer edit section *** (Subscription.EndTime Get start)

                //  *** End programmer edit section *** (Subscription.EndTime Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fEndTime;
                //  *** Start programmer edit section *** (Subscription.EndTime Get end)

                //  *** End programmer edit section *** (Subscription.EndTime Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Subscription.EndTime Set start)

                //  *** End programmer edit section *** (Subscription.EndTime Set start)
                this.fEndTime = value;
                //  *** Start programmer edit section *** (Subscription.EndTime Set end)

                //  *** End programmer edit section *** (Subscription.EndTime Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        //  *** Start programmer edit section *** (Subscription.ServiceCount CustomAttributes)

        //  *** End programmer edit section *** (Subscription.ServiceCount CustomAttributes)
        [NotNull()]
        public virtual double ServiceCount
        {
            get
            {
                //  *** Start programmer edit section *** (Subscription.ServiceCount Get start)

                //  *** End programmer edit section *** (Subscription.ServiceCount Get start)
                double result = this.fServiceCount;
                //  *** Start programmer edit section *** (Subscription.ServiceCount Get end)

                //  *** End programmer edit section *** (Subscription.ServiceCount Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Subscription.ServiceCount Set start)

                //  *** End programmer edit section *** (Subscription.ServiceCount Set start)
                this.fServiceCount = value;
                //  *** Start programmer edit section *** (Subscription.ServiceCount Set end)

                //  *** End programmer edit section *** (Subscription.ServiceCount Set end)
            }
        }
        
        /// <summary>
        /// Subscription.
        /// </summary>
        //  *** Start programmer edit section *** (Subscription.Service CustomAttributes)

        //  *** End programmer edit section *** (Subscription.Service CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.DigitalSubscription.Service Service
        {
            get
            {
                //  *** Start programmer edit section *** (Subscription.Service Get start)

                //  *** End programmer edit section *** (Subscription.Service Get start)
                NewPlatform.DigitalSubscription.Service result = this.fService;
                //  *** Start programmer edit section *** (Subscription.Service Get end)

                //  *** End programmer edit section *** (Subscription.Service Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Subscription.Service Set start)

                //  *** End programmer edit section *** (Subscription.Service Set start)
                this.fService = value;
                //  *** Start programmer edit section *** (Subscription.Service Set end)

                //  *** End programmer edit section *** (Subscription.Service Set end)
            }
        }
        
        /// <summary>
        /// Subscription.
        /// </summary>
        //  *** Start programmer edit section *** (Subscription.Client CustomAttributes)

        //  *** End programmer edit section *** (Subscription.Client CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.DigitalSubscription.ApplicationUser Client
        {
            get
            {
                //  *** Start programmer edit section *** (Subscription.Client Get start)

                //  *** End programmer edit section *** (Subscription.Client Get start)
                NewPlatform.DigitalSubscription.ApplicationUser result = this.fClient;
                //  *** Start programmer edit section *** (Subscription.Client Get end)

                //  *** End programmer edit section *** (Subscription.Client Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Subscription.Client Set start)

                //  *** End programmer edit section *** (Subscription.Client Set start)
                this.fClient = value;
                //  *** Start programmer edit section *** (Subscription.Client Set end)

                //  *** End programmer edit section *** (Subscription.Client Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SubscriptionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubscriptionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubscriptionE", typeof(NewPlatform.DigitalSubscription.Subscription));
                }
            }
            
            /// <summary>
            /// "SubscriptionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubscriptionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubscriptionL", typeof(NewPlatform.DigitalSubscription.Subscription));
                }
            }
        }
    }
}
