//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.DigitalSubscription
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Visit.
    /// </summary>
    //  *** Start programmer edit section *** (Visit CustomAttributes)

    //  *** End programmer edit section *** (Visit CustomAttributes)
    [BusinessServer("NewPlatform.DigitalSubscription.VisitBS, DigitalSubscription.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [PublishName("Visit")]
    [AutoAltered()]
    [Caption("Посещение")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("VisitE", new string[] {
            "Date as \'Дата\'",
            "Subscription as \'Услуга\'",
            "Subscription.StartTime as \'С\'",
            "Subscription.EndTime as \'По\'",
            "Subscription.Service.Name",
            "Subscription.Service.Organization.Name as \'Организация\'",
            "Client as \'Email\'",
            "Client.Email as \'Email\'",
            "Client.LastName as \'Фамилия\'",
            "Client.FirstName as \'Имя\'",
            "Client.MiddleName as \'Отчество\'"}, Hidden=new string[] {
            "Subscription.Service.Name",
            "Client.Email"})]
    [MasterViewDefineAttribute("VisitE", "Subscription", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Service.Name")]
    [MasterViewDefineAttribute("VisitE", "Client", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Email")]
    [View("VisitL", new string[] {
            "Date as \'Дата\'",
            "Subscription.Service.Name as \'Услуга\'",
            "Client.Email as \'Email\'",
            "Client.LastName as \'Фамилия\'",
            "Client.FirstName as \'Имя\'",
            "Client.MiddleName as \'Отчество\'",
            "Client.Birthdate as \'Дата рождения\'"})]
    public class Visit : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDate = System.DateTime.Now;
        
        private NewPlatform.DigitalSubscription.Subscription fSubscription;
        
        private NewPlatform.DigitalSubscription.ApplicationUser fClient;
        
        //  *** Start programmer edit section *** (Visit CustomMembers)

        //  *** End programmer edit section *** (Visit CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (Visit.Date CustomAttributes)

        //  *** End programmer edit section *** (Visit.Date CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Date
        {
            get
            {
                //  *** Start programmer edit section *** (Visit.Date Get start)

                //  *** End programmer edit section *** (Visit.Date Get start)
                System.DateTime result = this.fDate;
                //  *** Start programmer edit section *** (Visit.Date Get end)

                //  *** End programmer edit section *** (Visit.Date Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Visit.Date Set start)

                //  *** End programmer edit section *** (Visit.Date Set start)
                this.fDate = value;
                //  *** Start programmer edit section *** (Visit.Date Set end)

                //  *** End programmer edit section *** (Visit.Date Set end)
            }
        }
        
        /// <summary>
        /// Visit.
        /// </summary>
        //  *** Start programmer edit section *** (Visit.Subscription CustomAttributes)

        //  *** End programmer edit section *** (Visit.Subscription CustomAttributes)
        [PropertyStorage(new string[] {
                "Subscription"})]
        [NotNull()]
        public virtual NewPlatform.DigitalSubscription.Subscription Subscription
        {
            get
            {
                //  *** Start programmer edit section *** (Visit.Subscription Get start)

                //  *** End programmer edit section *** (Visit.Subscription Get start)
                NewPlatform.DigitalSubscription.Subscription result = this.fSubscription;
                //  *** Start programmer edit section *** (Visit.Subscription Get end)

                //  *** End programmer edit section *** (Visit.Subscription Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Visit.Subscription Set start)

                //  *** End programmer edit section *** (Visit.Subscription Set start)
                this.fSubscription = value;
                //  *** Start programmer edit section *** (Visit.Subscription Set end)

                //  *** End programmer edit section *** (Visit.Subscription Set end)
            }
        }
        
        /// <summary>
        /// Visit.
        /// </summary>
        //  *** Start programmer edit section *** (Visit.Client CustomAttributes)

        //  *** End programmer edit section *** (Visit.Client CustomAttributes)
        [PropertyStorage(new string[] {
                "Client"})]
        [NotNull()]
        public virtual NewPlatform.DigitalSubscription.ApplicationUser Client
        {
            get
            {
                //  *** Start programmer edit section *** (Visit.Client Get start)

                //  *** End programmer edit section *** (Visit.Client Get start)
                NewPlatform.DigitalSubscription.ApplicationUser result = this.fClient;
                //  *** Start programmer edit section *** (Visit.Client Get end)

                //  *** End programmer edit section *** (Visit.Client Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Visit.Client Set start)

                //  *** End programmer edit section *** (Visit.Client Set start)
                this.fClient = value;
                //  *** Start programmer edit section *** (Visit.Client Set end)

                //  *** End programmer edit section *** (Visit.Client Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "VisitE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VisitE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VisitE", typeof(NewPlatform.DigitalSubscription.Visit));
                }
            }
            
            /// <summary>
            /// "VisitL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View VisitL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("VisitL", typeof(NewPlatform.DigitalSubscription.Visit));
                }
            }
        }
    }
}
