//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.DigitalSubscription
{
    using System;
    using System.Xml;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// VisitBS.
    /// </summary>
    //  *** Start programmer edit section *** (VisitBS CustomAttributes)

    //  *** End programmer edit section *** (VisitBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class VisitBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        //  *** Start programmer edit section *** (VisitBS CustomMembers)

        //  *** End programmer edit section *** (VisitBS CustomMembers)

        
        //  *** Start programmer edit section *** (OnUpdateVisit CustomAttributes)

        //  *** End programmer edit section *** (OnUpdateVisit CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateVisit(NewPlatform.DigitalSubscription.Visit UpdatedObject)
        {
            //  *** Start programmer edit section *** (OnUpdateVisit)

            return new ICSSoft.STORMNET.DataObject[0];
            //  *** End programmer edit section *** (OnUpdateVisit)
        }
    }
}
